### ISSUE TITLE
Cannot upgrade to latest

### ISSUE THREAD

**Issue by fbradyirl** [maorcc/hassio-addon-transmission#22] opened 2024-08-20 08:27 UTC
On Home Assistant Yellow hardware, I am unable to upgrade to the latest version.

> `Can't install ghcr.io/maorcc/aarch64-hassio-addon-transmission:1.2.4: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=1.2.4&fromImage=ghcr.io%2Fmaorcc%2Faarch64-hassio-addon-transmission&platform=linux%2Farm64: Internal Server Error ("manifest unknown")`

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/74a44d86-08e8-4f4d-bf55-28223808c5ad">

**Comment by TomK** [comment] 2024-08-20 10:33
i have the same issue with the amd64 image:

 > Can't install ghcr.io/maorcc/amd64-hassio-addon-transmission:1.2.4: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=1.2.4&fromImage=ghcr.io%2Fmaorcc%2Famd64-hassio-addon-transmission&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by ThePatricide** [comment] 2024-08-20 11:11
Same here, as commented in the upgrade pull:
https://github.com/maorcc/hassio-addon-transmission/pull/8

**Comment by maorcc** [comment] 2024-08-20 18:55
Hi. Please try to upgrade (to 1.2.5) and let me know if the issue is resolved.

**Comment by ThePatricide** [comment] 2024-08-20 19:24
I can confirm it has been fixed with 1.2.5 indeed, much appreciated!
________________________________

**Closed** 2024-08-20 20:28 UTC
Labels: bug
